package model;
// Generated 24/02/2020 18:58:49 by Hibernate Tools 4.3.1



/**
 * Lancamentos generated by hbm2java
 */
public class Lancamentos{


     private Integer cod;
     private String inscricao;
     private String proprietario;
     private String cpfPro;
     private String compromissario;
     private String cpfCom;
     private String logradouro;
     private String numero;
     private String bairro;
     private String cidade;
     private String uf;
     private String cep;
     private String quadra;
     private String lote;
     private int setor;
     private String padrao;
     private String tipo;
     private double terreno;
     private double construcao;

    public Lancamentos() {
    }

    public Lancamentos(String inscricao, String proprietario, String cpfPro, String compromissario, String cpfCom, String logradouro, String numero, String bairro, String cidade, String uf, String cep, String quadra, String lote, int setor, String padrao, String tipo, double terreno, double construcao) {
       this.inscricao = inscricao;
       this.proprietario = proprietario;
       this.cpfPro = cpfPro;
       this.compromissario = compromissario;
       this.cpfCom = cpfCom;
       this.logradouro = logradouro;
       this.numero = numero;
       this.bairro = bairro;
       this.cidade = cidade;
       this.uf = uf;
       this.cep = cep;
       this.quadra = quadra;
       this.lote = lote;
       this.setor = setor;
       this.padrao = padrao;
       this.tipo = tipo;
       this.terreno = terreno;
       this.construcao = construcao;
    }
    public void Cadastrar(String inscricao,String proprietario,String cpf_pro,String compromissario,String cpf_com,String logradouro,String numero,String bairro,String cidade,String uf,String cep,String quadra,String lote,Integer setor,String padrao,String tipo,Double terreno,Double construcao){
        this.setBairro(bairro);
        this.setCep(cep);
        this.setCidade(cidade);
        this.setCompromissario(compromissario);
        this.setConstrucao(construcao);
        this.setCpfCom(cpf_com);
        this.setCpfPro(cpf_pro);
        this.setInscricao(inscricao);
        this.setLogradouro(logradouro);
        this.setLote(lote);
        this.setNumero(numero);
        this.setPadrao(padrao);
        this.setProprietario(proprietario);
        this.setQuadra(quadra);
        this.setSetor(setor);
        this.setTerreno(terreno);
        this.setTipo(tipo);
        this.setUf(uf);
        
    }
    
    public void alterar(Integer cod,String inscricao,String proprietario,String cpf_pro,String compromissario,String cpf_com,String logradouro,String numero,String bairro,String cidade,String uf,String cep,String quadra,String lote,Integer setor,String padrao,String tipo,Double terreno,Double construcao){
        this.setCod(cod);
        this.setBairro(bairro);
        this.setCep(cep);
        this.setCidade(cidade);
        this.setCompromissario(compromissario);
        this.setConstrucao(construcao);
        this.setCpfCom(cpf_com);
        this.setCpfPro(cpf_pro);
        this.setInscricao(inscricao);
        this.setLogradouro(logradouro);
        this.setLote(lote);
        this.setNumero(numero);
        this.setPadrao(padrao);
        this.setProprietario(proprietario);
        this.setQuadra(quadra);
        this.setSetor(setor);
        this.setTerreno(terreno);
        this.setTipo(tipo);
        this.setUf(uf);
    }
   
    public String[] addTable(){
        String[] dados = new String[]{String.valueOf(getCod()),getInscricao(),getProprietario(),getCpfPro(),getCompromissario(),getCpfCom(),getLogradouro(),getNumero(),getBairro(),getLote(),getQuadra()};
        return dados;        
    }
    
    public boolean camposVazio(String inscricao,String proprietario,String cpf_pro,String compromissario,String cpf_com,String logradouro,String numero,String bairro,String cidade,String uf,String cep,String quadra,String lote,Integer setor,String padrao,String tipo,Double terreno,Double construcao){
        if(inscricao.equals(" ") || proprietario.equals(" ") || cpf_pro.equals(" ") || compromissario.equals(" ") || cpf_com.equals(" ") || logradouro.equals(" ") || numero.equals(" ") || bairro.equals(" ") || cidade.equals(" ") || uf.equals(" ") || cep.equals(" ") || quadra.equals(" ") || lote.equals(" ") || setor.equals(" ")  || padrao.equals(" ") || tipo.equals(" ") || terreno.equals(" ") || construcao.equals(" ")){
            return false;
        }
        else{
            return true;
        }
    }
    
    public Integer getCod() {
        return this.cod;
    }
    
    public void setCod(Integer cod) {
        this.cod = cod;
    }
    public String getInscricao() {
        return this.inscricao;
    }
    
    public void setInscricao(String inscricao) {
        this.inscricao = inscricao;
    }
    public String getProprietario() {
        return this.proprietario;
    }
    
    public void setProprietario(String proprietario) {
        this.proprietario = proprietario;
    }
    public String getCpfPro() {
        return this.cpfPro;
    }
    
    public void setCpfPro(String cpfPro) {
        this.cpfPro = cpfPro;
    }
    public String getCompromissario() {
        return this.compromissario;
    }
    
    public void setCompromissario(String compromissario) {
        this.compromissario = compromissario;
    }
    public String getCpfCom() {
        return this.cpfCom;
    }
    
    public void setCpfCom(String cpfCom) {
        this.cpfCom = cpfCom;
    }
    public String getLogradouro() {
        return this.logradouro;
    }
    
    public void setLogradouro(String logradouro) {
        this.logradouro = logradouro;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public String getUf() {
        return this.uf;
    }
    
    public void setUf(String uf) {
        this.uf = uf;
    }
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }
    public String getQuadra() {
        return this.quadra;
    }
    
    public void setQuadra(String quadra) {
        this.quadra = quadra;
    }
    public String getLote() {
        return this.lote;
    }
    
    public void setLote(String lote) {
        this.lote = lote;
    }
    public int getSetor() {
        return this.setor;
    }
    
    public void setSetor(int setor) {
        this.setor = setor;
    }
    public String getPadrao() {
        return this.padrao;
    }
    
    public void setPadrao(String padrao) {
        this.padrao = padrao;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public double getTerreno() {
        return this.terreno;
    }
    
    public void setTerreno(double terreno) {
        this.terreno = terreno;
    }
    public double getConstrucao() {
        return this.construcao;
    }
    
    public void setConstrucao(double construcao) {
        this.construcao = construcao;
    }




}


